"""
This type stub file was generated by pyright.
"""

from .core import (
    DEFAULT_SETTINGS,
    ENOVAL,
    EVICTION_POLICY,
    UNKNOWN,
    Cache,
    Disk,
    EmptyDirWarning,
    JSONDisk,
    Timeout,
    UnknownFileWarning,
)
from .djangocache import DjangoCache
from .fanout import FanoutCache
from .persistent import Deque, Index
from .recipes import (
    Averager,
    BoundedSemaphore,
    Lock,
    RLock,
    barrier,
    memoize_stampede,
    throttle,
)

"""
DiskCache API Reference
=======================

The :doc:`tutorial` provides a helpful walkthrough of most methods.
"""
__all__ = [
    "DEFAULT_SETTINGS",
    "ENOVAL",
    "EVICTION_POLICY",
    "UNKNOWN",
    "Averager",
    "BoundedSemaphore",
    "Cache",
    "Deque",
    "Disk",
    "EmptyDirWarning",
    "FanoutCache",
    "Index",
    "JSONDisk",
    "Lock",
    "RLock",
    "Timeout",
    "UnknownFileWarning",
    "barrier",
    "memoize_stampede",
    "throttle",
]
__title__ = ...
__version__ = ...
__build__ = ...
__author__ = ...
__license__ = ...
__copyright__ = ...
